# CUDA 12 on aarch needs newer glibc, which requires us to override
# the whole monster zip just to bump c_stdlib_version / docker_image
c_stdlib_version:                                   # [linux and aarch64]
  - 2.17                                            # [linux and aarch64]
